### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SpyC0der77** [shuttleai/shuttleai-python#11]
Traceback (most recent call last):
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpx\_transports\default.py", line 250, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpcore\_sync\connection_pool.py", line 256, in handle_request
    raise exc from None
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpcore\_sync\connection_pool.py", line 236, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpcore\_sync\connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpcore\_sync\http11.py", line 136, in handle_request
    raise exc
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpcore\_sync\http11.py", line 106, in handle_request
    ) = self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpcore\_sync\http11.py", line 177, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpcore\_sync\http11.py", line 217, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpcore\_backends\sync.py", line 126, in read
    with map_exceptions(exc_map):
  File "C:\Python312\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(value)
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\shuttleai\client\_sync.py", line 150, in _request
    response = self._http_client.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpx\_client.py", line 825, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpx\_client.py", line 1014, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpx\_transports\default.py", line 249, in handle_request
    with map_httpcore_exceptions():
  File "C:\Python312\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(value)
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\httpx\_transports\default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\generate.py", line 18, in <module>
    chat_completion = shuttleai.chat.completions.create(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\shuttleai\resources\chat\completions.py", line 150, in create
    return self.handle_request(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\shuttleai\resources\common.py", line 46, in handle_request
    return self._no_stream_response(response, response_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\shuttleai\resources\common.py", line 24, in _no_stream_response
    for resp in response:
  File "C:\Users\Carter\Code\Full Projects\Podcast2Newsletter\.venv\Lib\site-packages\shuttleai\client\_sync.py", line 162, in _request
    raise ShuttleAIException(f"Unexpected exception ({e.__class__.__name__}): {e}") from e
shuttleai.exceptions.ShuttleAIException: Unexpected exception (ReadTimeout): The read operation timed out
PS C:\Users\Carter\Code\Full Projects\Podcast2Newsletter>

**Comment by SpyC0der77** [comment]
I still have this issue

**Comment by SpyC0der77** [comment]
I still have the issue @herumes
